kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  annotations:
    haproxy.router.openshift.io/timeout: 10h
spec:
  tls:
    - hosts:
        - {{ include "atp3tdm.ingressHost" . }}
  rules:
    - host: '{{ include "atp3tdm.ingressHost" . }}'
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                port:
                  number: 8080
                name: '{{ .Values.SERVICE_NAME }}'
